{% set name = "libtiledb-sql-py" %}
{% set version = "2.1.0" %}
{% set sha256 = "3683dc495f8defe147205f42547ed0a274e1ff10305bf21d1da7fdef23366802" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/TileDB-SQL-Py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - wheel
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - libtiledb-sql
  run:
    - python
    - libtiledb-sql

test:
  imports:
    - tiledb.sql
  commands:
    - python -c "import tiledb.sql"

about:
  home: https://tiledb.com
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: libtiledb-sql-py is a Embedded Python SQL interface for TileDB arrays using the MyTile storage engine
  description: |
    libtiledb-sql-py is a fork of the mysqlclient-python which builds against libtiledb-sql to provide embedded sql querying of TileDB arrays.\n

    Docs: https://docs.tiledb.com/developer/api-usage/embedded-sql

    Source: https://github.com/TileDB-Inc/TileDB-SQL-Py

    Upstream source: https://github.com/PyMySQL/mysqlclient-python

  doc_url: https://docs.tiledb.com/developer/api-usage/embedded-sql
  dev_url: https://github.com/TileDB-Inc/TileDB-SQL-Py

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
