{% set name = "libtiledb-sql-py" %}
{% set version = "2.1.3" %}
{% set sha256 = "84595ff052d37314dc73b71a4b231f23b978be3a647a3e07529e3cfe5c080c57" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/TileDB-SQL-Py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: true  # [win]
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - mysql                                 # [build_platform != target_platform]
  host:
    - python
    - wheel
    - setuptools
    - setuptools_scm 6.0.1
    - setuptools_scm_git_archive
    - libtiledb-sql >=0.10
    - libxcrypt                             # [linux]
  run:
    - python
    - libtiledb-sql >=0.10
test:
  imports:
    - tiledb.sql
  commands:
    - python -c "import tiledb.sql"

about:
  home: https://tiledb.com
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: libtiledb-sql-py is a Embedded Python SQL interface for TileDB arrays using the MyTile storage engine
  description: |
    libtiledb-sql-py is a fork of the mysqlclient-python which builds against libtiledb-sql to provide embedded sql querying of TileDB arrays.\n

    Docs: https://docs.tiledb.com/developer/api-usage/embedded-sql

    Source: https://github.com/TileDB-Inc/TileDB-SQL-Py

    Upstream source: https://github.com/PyMySQL/mysqlclient-python

  doc_url: https://docs.tiledb.com/developer/api-usage/embedded-sql
  dev_url: https://github.com/TileDB-Inc/TileDB-SQL-Py

extra:
  recipe-maintainers:
    - DimitrisStaratzis
    - shelnutt2
    - ihnorton
