build_platform:
  osx_arm64: osx_64
provider:
  linux_aarch64: azure
conda_forge_output_validation: true
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
